#ifndef HELLOKERNCONTROL_HPP
#define HELLOKERNCONTROL_HPP

#define BUNDLE_ID "com.bugratest.HelloKernControl"

#define HELLO_CONTROL_GET_STRING 1
#define HELLO_CONTROL_SET_STRING 2

#define DEFAULT_STRING "Hello World"
#define MAX_STRING_LEN 256

#endif /* HELLOKERNCONTROL_HPP */
